### ISSUE TITLE
Menu fails if input not understandable by logic

### ISSUE THREAD

**Issue by StephenBannister** [StephenBannister/celestial_system#1]
Entering dgfsdgfsdfgd into the menu results in an error:

2024-11-26 20:37:54,665 - INFO - Solar system created successfully
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\StephenBannister\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\StephenBannister\OneDrive\Files\Uni\Sheffield Hallam\MSc\Module1\celestial_system\celestial_system\system_menu.py", line 115, in process_input
    choice, planet_choice = self.determine_menu_choice(user_input)
    ^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\StephenBannister\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\StephenBannister\OneDrive\Files\Uni\Sheffield Hallam\MSc\Module1\celestial_system\celestial_system\system_menu.py", line 115, in process_input
    choice, planet_choice = self.determine_menu_choice(user_input)
    ^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\StephenBannister\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\StephenBannister\OneDrive\Files\Uni\Sheffield Hallam\MSc\Module1\celestial_system\celestial_system\system_menu.py", line 115, in process_input
    choice, planet_choice = self.determine_menu_choice(user_input)
    ^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

**Comment by StephenBannister** [comment]
Tracing through the code reveals that if no planet is identified in a users input, and no keywords are matched for the NLP dictionary, the a single None was returned to a call requiring 2 parameters to be returned. Adjusted code in system_menu to return None, None to match required variable equality.
